title: Offshorly
default_lang: en
author:
  name: 'John Appleseed'
  email: chris@offshorly.com
taxonomies:
  - category
  - tag
metadata:
  description: 'offshore web outsource'
  keywords: 'offshorly, offshore, web, outsource'
  generator: GravCMS
  robots: 'index, follow'
  theme-color: '#009275'
  google-site-verification: xcwuZNo5pIJg3acdhtxhyFCMaETtpSFQ1Uoeuo-LCTI
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
